/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Calculadora;
import util.Arquivo;

/**
 *
 * @author Alex
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFNum1 = new javax.swing.JTextField();
        JTFNum2 = new javax.swing.JTextField();
        JTFResultado = new javax.swing.JTextField();
        jButtonDividir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAHistorico = new javax.swing.JTextArea();
        jButtonExcluirHistorico = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonSomar = new javax.swing.JButton();
        jButtonSubtrair = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("numero 1");

        jLabel2.setText("numero 2");

        JTFNum1.setBackground(new java.awt.Color(0, 0, 0));
        JTFNum1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFNum1.setForeground(new java.awt.Color(255, 255, 255));
        JTFNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNum1ActionPerformed(evt);
            }
        });

        JTFNum2.setBackground(new java.awt.Color(0, 0, 0));
        JTFNum2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFNum2.setForeground(new java.awt.Color(255, 255, 255));

        JTFResultado.setBackground(new java.awt.Color(0, 0, 0));
        JTFResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTFResultado.setForeground(new java.awt.Color(255, 255, 255));
        JTFResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFResultadoActionPerformed(evt);
            }
        });

        jButtonDividir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDividir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDividir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDividir.setText("Dividir /");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        JTAHistorico.setBackground(new java.awt.Color(0, 0, 0));
        JTAHistorico.setColumns(20);
        JTAHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JTAHistorico.setForeground(new java.awt.Color(255, 255, 255));
        JTAHistorico.setRows(5);
        jScrollPane1.setViewportView(JTAHistorico);

        jButtonExcluirHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jButtonExcluirHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluirHistorico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluirHistorico.setText("Excluir Histórico");
        jButtonExcluirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirHistoricoActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiplicar.setText("Multiplicar *");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButtonSomar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSomar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSomar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSomar.setText("Somar +");
        jButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomarActionPerformed(evt);
            }
        });

        jButtonSubtrair.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSubtrair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubtrair.setText("Subtrair -");
        jButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtrairActionPerformed(evt);
            }
        });

        jButtonHistorico.setBackground(new java.awt.Color(0, 0, 0));
        jButtonHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHistorico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHistorico.setText("Histórico");
        jButtonHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(JTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLimpar))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluirHistorico))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonSomar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHistorico))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                        .addComponent(JTFResultado)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSomar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonMultiplicar)
                                    .addComponent(jButtonDividir)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimpar)
                            .addComponent(jButtonExcluirHistorico)
                            .addComponent(jButtonHistorico)))
                    .addComponent(jButtonSubtrair))
                .addGap(10, 10, 10)
                .addComponent(JTFResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNum1ActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        // TODO add your handling code here:
        if(JTFNum1.getText().trim().isEmpty() || JTFNum2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFNum1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFNum1.getText());
            double num2 = Double.parseDouble(JTFNum2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.dividir(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " / " + num2 +" = " + resultado + "\n");
            String linha = num1 + " / " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
          
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        
        JTFNum1.setText("");
        JTFNum2.setText("");
        JTFResultado.setText("");
        JTFNum1.requestFocus(); 
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void JTFResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFResultadoActionPerformed

    private void jButtonExcluirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirHistoricoActionPerformed
        boolean sucesso = Arquivo.excluirArquivo("Historico.txt");
        if (sucesso) {
            javax.swing.JOptionPane.showMessageDialog(this, "Arquivo 'Historico.txt' excluído com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            JTAHistorico.setText(""); // Limpa o JTAHistorico / o arquivo foi excluído
        } else {
            // Se o método retornar false, significa que o arquivo não existia, ou houve erro de permissão, etc.
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Falha ao excluir o arquivo 'Historico.txt'. Verifique se ele existe e não está em uso.", 
                "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }       
        JTFNum1.requestFocus(); 
        JTAHistorico.setText("");
        JTFNum1.requestFocus();
    }//GEN-LAST:event_jButtonExcluirHistoricoActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        // TODO add your handling code here:
        if(JTFNum1.getText().trim().isEmpty() || JTFNum2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFNum1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFNum1.getText());
            double num2 = Double.parseDouble(JTFNum2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.multiplicar(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " x " + num2 +" = " + resultado + "\n");
            String linha = num1 + " * " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomarActionPerformed
        // TODO add your handling code here:
        if(JTFNum1.getText().trim().isEmpty() || JTFNum2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFNum1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFNum1.getText());
            double num2 = Double.parseDouble(JTFNum2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.somar(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " + " + num2 +" = " + resultado + "\n");
            String linha = num1 + " + " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSomarActionPerformed

    private void jButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtrairActionPerformed
        // TODO add your handling code here:
        if(JTFNum1.getText().trim().isEmpty() || JTFNum2.getText().trim().isEmpty()){
            JTFResultado.setText("Preencha todos os campos");
            JTAHistorico.setText("preencha todos os campos");
            JTFNum1.requestFocus();
            return;
        }
        try{
            double num1 = Double.parseDouble(JTFNum1.getText());
            double num2 = Double.parseDouble(JTFNum2.getText());
            
            Calculadora calculadora = new Calculadora();
            double resultado = calculadora.subtrair(num1,num2);
            
            JTFResultado.setText("resultado: "+ resultado);
            
            JTAHistorico.append(num1 + " - " + num2 +" = " + resultado + "\n");
            String linha = num1 + " - " + num2 + " = " + resultado;
            Arquivo.salvarLinha(linha);
        }
        catch(NumberFormatException ex){
            JTFResultado.setText("digite apenas valor numerico");
        }
        catch(ArithmeticException ex){
            JTFResultado.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSubtrairActionPerformed

    private void jButtonHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoActionPerformed
        new viewSecundaria().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTAHistorico;
    private javax.swing.JTextField JTFNum1;
    private javax.swing.JTextField JTFNum2;
    private javax.swing.JTextField JTFResultado;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonExcluirHistorico;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
